insert into maker_dim (uk, name) values (get_uk, 'Acura');
insert into maker_dim (uk, name) values (get_uk, 'Alfa Romeo');
insert into maker_dim (uk, name) values (get_uk, 'Aston Martin');
insert into maker_dim (uk, name) values (get_uk, 'Audi');
insert into maker_dim (uk, name) values (get_uk, 'Bentley');
insert into maker_dim (uk, name) values (get_uk, 'BMW');
insert into maker_dim (uk, name) values (get_uk, 'Buick');
insert into maker_dim (uk, name) values (get_uk, 'Cadillac');
insert into maker_dim (uk, name) values (get_uk, 'Chery');
insert into maker_dim (uk, name) values (get_uk, 'Chevrolet');
insert into maker_dim (uk, name) values (get_uk, 'Chrysler');
insert into maker_dim (uk, name) values (get_uk, 'Citroen');
insert into maker_dim (uk, name) values (get_uk, 'Daewoo');
insert into maker_dim (uk, name) values (get_uk, 'Daihatsu');
insert into maker_dim (uk, name) values (get_uk, 'Dodge');
insert into maker_dim (uk, name) values (get_uk, 'FAW');
insert into maker_dim (uk, name) values (get_uk, 'Ferrari');
insert into maker_dim (uk, name) values (get_uk, 'Fiat');
insert into maker_dim (uk, name) values (get_uk, 'Ford');
insert into maker_dim (uk, name) values (get_uk, 'Geely');
insert into maker_dim (uk, name) values (get_uk, 'GMC');
insert into maker_dim (uk, name) values (get_uk, 'Great Wall');
insert into maker_dim (uk, name) values (get_uk, 'Honda');
insert into maker_dim (uk, name) values (get_uk, 'Hummer');
insert into maker_dim (uk, name) values (get_uk, 'Hyundai');
insert into maker_dim (uk, name) values (get_uk, 'Infiniti');
insert into maker_dim (uk, name) values (get_uk, 'Isuzu');
insert into maker_dim (uk, name) values (get_uk, 'Jaguar');
insert into maker_dim (uk, name) values (get_uk, 'Jeep');
insert into maker_dim (uk, name) values (get_uk, 'Kia');
insert into maker_dim (uk, name) values (get_uk, 'Lamborghini');
insert into maker_dim (uk, name) values (get_uk, 'Lancia');
insert into maker_dim (uk, name) values (get_uk, 'Land Rover');
insert into maker_dim (uk, name) values (get_uk, 'Lexus');
insert into maker_dim (uk, name) values (get_uk, 'Lifan');
insert into maker_dim (uk, name) values (get_uk, 'Lincoln');
insert into maker_dim (uk, name) values (get_uk, 'Lotus');
insert into maker_dim (uk, name) values (get_uk, 'Marussia');
insert into maker_dim (uk, name) values (get_uk, 'Maserati');
insert into maker_dim (uk, name) values (get_uk, 'Maybach');
insert into maker_dim (uk, name) values (get_uk, 'Mazda');
insert into maker_dim (uk, name) values (get_uk, 'McLaren');
insert into maker_dim (uk, name) values (get_uk, 'Mercedes');
insert into maker_dim (uk, name) values (get_uk, 'Mercury');
insert into maker_dim (uk, name) values (get_uk, 'MG');
insert into maker_dim (uk, name) values (get_uk, 'Mini');
insert into maker_dim (uk, name) values (get_uk, 'Mitsubishi');
insert into maker_dim (uk, name) values (get_uk, 'Nissan');
insert into maker_dim (uk, name) values (get_uk, 'Opel');
insert into maker_dim (uk, name) values (get_uk, 'Peugeot');
insert into maker_dim (uk, name) values (get_uk, 'Pontiac');
insert into maker_dim (uk, name) values (get_uk, 'Porsche');
insert into maker_dim (uk, name) values (get_uk, 'Renault');
insert into maker_dim (uk, name) values (get_uk, 'Rolls-Royce');
insert into maker_dim (uk, name) values (get_uk, 'Rover');
insert into maker_dim (uk, name) values (get_uk, 'Saab');
insert into maker_dim (uk, name) values (get_uk, 'Saturn');
insert into maker_dim (uk, name) values (get_uk, 'Scion');
insert into maker_dim (uk, name) values (get_uk, 'Seat');
insert into maker_dim (uk, name) values (get_uk, 'Skoda');
insert into maker_dim (uk, name) values (get_uk, 'Smart');
insert into maker_dim (uk, name) values (get_uk, 'Ssang Yong');
insert into maker_dim (uk, name) values (get_uk, 'Subaru');
insert into maker_dim (uk, name) values (get_uk, 'Suzuki');
insert into maker_dim (uk, name) values (get_uk, 'Tesla');
insert into maker_dim (uk, name) values (get_uk, 'Toyota');
insert into maker_dim (uk, name) values (get_uk, 'Volkswagen');
insert into maker_dim (uk, name) values (get_uk, 'Volvo');
insert into maker_dim (uk, name) values (get_uk, 'ВАЗ');
insert into maker_dim (uk, name) values (get_uk, 'ГАЗ');
insert into maker_dim (uk, name) values (get_uk, 'УАЗ');

commit;
